apiVersion: v1
kind: Secret
metadata:
  name: product-postgresql
  namespace: jhipster
  labels:
    app: product-postgresql
type: Opaque
data:
  postgresql-password: ZjA4MjI3MDI0ZmU2OWQzOWVkM2U2YWM3ODliOTVlYTRlYmE1MzhiYjFjMDI0MTUwYWVkNTg3MmNiZDE4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-postgresql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-postgresql
  template:
    metadata:
      labels:
        app: product-postgresql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:14.2
          env:
            - name: POSTGRES_USER
              value: product
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: product-postgresql
  namespace: jhipster
spec:
  selector:
    app: product-postgresql
  ports:
    - port: 5432
