# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  notification-app:
    image: notification
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://notification-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=notification
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  notification-mongodb:
    image: mongo:4.4.12
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/jhipster/notification/mongodb/:/data/db/
