# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  store-app:
    image: store
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_R2DBC_URL=r2dbc:postgresql://store-postgresql:5432/store
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://store-postgresql:5432/store
      - JHIPSTER_SLEEP=60 # gives time for microservices to boot before the gateway, the entire stack will be ready to accept incomming requests.
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  store-postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/jhipster/store/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
