# apiVersion: security.istio.io/v1beta1
# kind: RequestAuthentication
# metadata:
#   name: product
#   namespace: jhipster
# spec:
#   selector:
#     matchLabels:
#       app: product
#   jwtRules:
#   - issuer: https://dev-7163545.okta.com/oauth2/default
#     jwksUri: https://dev-7163545.okta.com/oauth2/default/v1/keys
# ---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: product
#   namespace: jhipster
# spec:
#   selector:
#     matchLabels:
#       app: product
#   # action: CUSTOM
#   # provider:
#   #   # Extension provider configured when we installed Istio
#   #   name: oauth2-proxy
#   rules:
#   - from:
#     - source:
#         requestPrincipals: ["*"]
